### ISSUE TITLE
适配dfi2.0

### ISSUE THREAD

**Issue by jin10086** [yfii/yfii-stats#1]
合约地址数据在：https://raw.githubusercontent.com/yfii/yvault/master/contracts/standard/v2/config.json

其中vault是合约地址

![image](https://user-images.githubusercontent.com/15347911/93158810-7c61b580-f73f-11ea-8ca4-bf68ed9ae2b9.png)

需要先查token方法，拿到里面存的是哪个币

然后查 balance 得到存入的数量

再乘以价格就是TVL了

apy的接口在https://api.dfi.money/apy.json

**Comment by jin10086** [comment]
价格可以用 https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,curve-dao-token,yfii-finance&vs_currencies=usd 的一次性可以查多个币种的

**Comment by soulmachine** [comment]
I can take this task

**Comment by soulmachine** [comment]
I'll make a pull request to this repo
